# Generated by Django 3.1.7 on 2021-05-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='title',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='projects',
            name='analysis',
            field=models.CharField(max_length=2000, verbose_name='Ситуация'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='curator',
            field=models.CharField(max_length=45, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='problem',
            field=models.CharField(max_length=2000, verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.ManyToManyField(related_name='project', to='problems.Users', verbose_name='Руководитель проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='shortdescription',
            field=models.CharField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=90, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
